### ISSUE TITLE
Jeudi 16/02

### ISSUE THREAD

**Issue by lmilhade** [Vayel/wello#10]
Schéma de la maquette
  ---> Liste de courses

Création du wiki, au moins les pages de présentation du problème/situation initiale

Création de la page sur le site du FabLab

[C'est une idée, à compléter]

**Comment by Vayel** [comment]
#5

**Comment by Vayel** [comment]
https://github.com/Vayel/wello/wiki/Syst%C3%A8me-actuel

**Comment by Vayel** [comment]
https://github.com/Vayel/wello/wiki/Probl%C3%A9matique
