### ISSUE TITLE
Commande de matériel

### ISSUE THREAD

**Issue by lmilhade** [Vayel/wello#12]
Bonjour monsieur,

Pour la réalisation de la maquette de notre projet, vous nous avez suggéré de vous donner une liste des composants dont nous aurions besoin et qui ne sont pas disponibles au FabLab.
Comme précisé dans le wiki de la maquette (https://github.com/Vayel/wello/wiki/Maquette), nous aurions besoin: 
 - D'une pompe : https://www.amazon.fr/MISOL-Circulation-Brushless-syst%C2%A8%C2%A8me-circulation/dp/B00NATVFYS/ref=sr_1_3?ie=UTF8&qid=1487260368&sr=8-3&keywords=pompe+eau+1%2F2%22
 - De deux débitmètres : https://www.amazon.fr/SODIAL-Capteur-Debitmetre-controle-2-0MPa/dp/B00K67YL98/ref=sr_1_3?ie=UTF8&qid=1487262020&sr=8-3&keywords=debimetre
 - D'une électrovanne : https://www.amazon.fr/pouce-Electrovanne-Electrique-Carburants-Normalement/dp/B00R2J9HCY/ref=pd_cp_60_1?_encoding=UTF8&psc=1&refRID=FHX8EMYEGM596F2VGQCW

**Comment by Vayel** [comment]
Bonjour monsieur,

Dans le cadre de notre projet FabLab de gestion d'eau d'un puits pour une ferme, nous souhaiterions réaliser une maquette pour à la fois mieux appréhender le système physique et rendre notre présentation finale plus vivante.

Nous aurions ainsi besoin de certains composants probablement indisponibles au FabLab et vous nous avez demandé de vous en fournir une liste. Tout est détaillé sur la page wiki de la maquette (https://github.com/Vayel/wello/wiki/Maquette) ; nous en faisons un résumé ci-dessous : 

 - Une pompe : https://www.amazon.fr/MISOL-Circulation-Brushless-syst%C2%A8%C2%A8me-circulation/dp/B00NATVFYS/ref=sr_1_3?ie=UTF8&qid=1487260368&sr=8-3&keywords=pompe+eau+1%2F2%22
 - Deux débitmètres : https://www.amazon.fr/SODIAL-Capteur-Debitmetre-controle-2-0MPa/dp/B00K67YL98/ref=sr_1_3?ie=UTF8&qid=1487262020&sr=8-3&keywords=debimetre
- Un capteur à ultrason (déjà disponible au FabLab)
 - Une électrovanne : https://www.amazon.fr/pouce-Electrovanne-Electrique-Carburants-Normalement/dp/B00R2J9HCY/ref=pd_cp_60_1?_encoding=UTF8&psc=1&refRID=FHX8EMYEGM596F2VGQCW

Nous pensions également travailler avec une Arduino et une RPi, mais c'est moins problématique à priori.

Nous nous demandions également comment se passait l'accès au FabLab ainsi que l'utilisation du matériel.

Merci d'avance,

**Comment by lmilhade** [comment]
Pièces qui ne viennent pas d'amazon :

http://www.gotronic.fr/art-electrovanne-12-vcc-droite-ev12v-19587.htm
http://www.conrad.fr/ce/fr/product/539082/Pompe-submersible-basse-tension-Barwig-0333?ref=list
http://www.gotronic.fr/art-capteur-de-debit-yfs201-18979.htm
