### ISSUE TITLE
Sauvegarder les utilisations du réseau civil

### ISSUE THREAD

**Issue by Vayel** [Vayel/wello#31]
Pour savoir à quel point on l'utilise. Stocker les dates de commande de la pompe de sortie (quand elle est coupée, c'est qu'on est sur le réseau civil).

**Comment by denisrichard1996** [comment]
Stocker quand l'électrovanne est ouverte et que la cuve est vide* ?

**Comment by Vayel** [comment]
Juste quand la cuve est vide.
