### ISSUE TITLE
Déterminer le fonctionnement basique du système

### ISSUE THREAD

**Issue by Vayel** [Vayel/wello#5]
L'objectif est d'avoir un système fonctionnel rapidement pour se baser sur des résultats concrets et pourquoi pas commencer à le monter en vrai, ce qui permettrait d'avoir des mesures réelles par la suite.

**Comment by denisrichard1996** [comment]
L'électrovanne est controlé mécaniquement, ce n'est pas le système qui controle l'ouverture mais l'utilisateur (nous pendant la démo)
La cuve se vide donc seulement si l'électrovanne est ouverte
Si la cuve est vide et l'electrovanne est ouverte, on allume la led signifiant qu'il faut passer par le réseau civil
